# Generated by Django 5.0.6 on 2026-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('researcher', 'Researcher')], max_length=20, null=True),
        ),
    ]
